NesclPms.WebUI/Controllers/VehicleBillsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NesclPms.Domain.Concrete;
using NesclPms.Domain.Entities;
using NesclPms.Domain.Abstract;

namespace NesclPms.WebUI.Controllers
{
    [Authorize]
    public class VehicleBillsController : ApplicationController
    {
        private IEntitiesRepository repository;

        private EfDbContext db; // = new EFDbContext();

        public VehicleBillsController(IEntitiesRepository repo)
        {
            repository = repo;
            db = repository.Context;
        }
               

        // GET: VehicleBills
        public async Task<ActionResult> Index()
        {
            return View(await db.VehicleBills.ToListAsync());
        }

        // GET: VehicleBills/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VehicleBill vehicleBill = await db.VehicleBills.FindAsync(id);
            if (vehicleBill == null)
            {
                return HttpNotFound();
            }
            return View(vehicleBill);
        }

        // GET: VehicleBills/Create
        [Authorize(Roles="site_engg")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: VehicleBills/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID,Name,Date,Amount,Comments,IsPrepared,IsVerified,IsPassed")] VehicleBill vehicleBill)
        {
            if (ModelState.IsValid)
            {
                db.VehicleBills.Add(vehicleBill);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(vehicleBill);
        }

        // GET: VehicleBills/Edit/5
        [Authorize(Roles = "site_engg,srm,finance")]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VehicleBill vehicleBill = await db.VehicleBills.FindAsync(id);
            if (vehicleBill == null)
            {
                return HttpNotFound();
            }
            return View(vehicleBill);
        }

        // POST: VehicleBills/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,Name,Date,Amount,Comments,IsPrepared,IsVerified,IsPassed")] VehicleBill vehicleBill)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vehicleBill).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(vehicleBill);
        }

        // GET: VehicleBills/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VehicleBill vehicleBill = await db.VehicleBills.FindAsync(id);
            if (vehicleBill == null)
            {
                return HttpNotFound();
            }
            return View(vehicleBill);
        }

        // POST: VehicleBills/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            VehicleBill vehicleBill = await db.VehicleBills.FindAsync(id);
            db.VehicleBills.Remove(vehicleBill);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NesclPms.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("NESCL PMS", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Vehicle Bills", "Index", "VehicleBills")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    @if (User.IsInRole("admin"))
                    {
                        <li>@Html.ActionLink("Admin", "Index", "Admin")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <div class="footer">
            <p class="text-muted">&copy; @DateTime.Now.Year - NESCL</p>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>