NesclPms.WebUI/Controllers/AdminController.cs
using NesclPms.WebUI.Infrastructure;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.Owin;
using NesclPms.WebUI.Models;
using Microsoft.AspNet.Identity;
using System.Threading.Tasks;


namespace NesclPms.WebUI.Controllers
{
    [Authorize(Roles="admin")]
    public class AdminController : ApplicationController
    {
        public ActionResult Index()
        {
            return View(UserManager.Users);
        }

        private AppUserManager UserManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<AppUserManager>();
            }
        }

        public ActionResult Create() {
            
            return View();
        }
 
        [HttpPost]
        public async Task<ActionResult> Create(CreateModel model) {
            if (ModelState.IsValid) {
                AppUser user = new AppUser {UserName = model.Name, Email = model.Email, LabelName = model.LabelName};
                IdentityResult result = await UserManager.CreateAsync(user,
                    model.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    AddErrorsFromResult(result);
                }
            }
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(string id)
        {
            AppUser user = await UserManager.FindByIdAsync(id);
            if (user != null)
            {
                IdentityResult result = await UserManager.DeleteAsync(user);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return View("Error", result.Errors);
                }
            }
            else
            {
                return View("Error", new string[] { "User Not Found" });
            }
        }

         public async Task<ActionResult> Edit(string id) {
            AppUser user = await UserManager.FindByIdAsync(id);
            if (user != null) {
                return View(user);
            } else {
                return RedirectToAction("Index");
            }
        }
 
        [HttpPost]
        public async Task<ActionResult> Edit(string id, string labelName, string email) {
            AppUser user = await UserManager.FindByIdAsync(id);
            if (user != null) {
                user.LabelName = labelName;
                user.Email = email;
                IdentityResult validEmail
                    = await UserManager.UserValidator.ValidateAsync(user);
                if (!validEmail.Succeeded) {
                    AddErrorsFromResult(validEmail);
                }
                //IdentityResult validPass = null;
                //if (password != null && password != string.Empty) {
                //    validPass
                //        = await UserManager.PasswordValidator.ValidateAsync(password);
                //    if (validPass.Succeeded) {
                //        user.PasswordHash =
                //            UserManager.PasswordHasher.HashPassword(password);
                //    } else {
                //        AddErrorsFromResult(validPass);
                //    }
                //}
                if (validEmail.Succeeded) {
                    IdentityResult result = await UserManager.UpdateAsync(user);
                    if (result.Succeeded) {
                        return RedirectToAction("Index");
                    } else {
                        AddErrorsFromResult(result);
                    }
                }
            }
            else
            {
                ModelState.AddModelError("", "User Not Found");
            }
            return View(user);
        }

        private void AddErrorsFromResult(IdentityResult result)
        {
            foreach (string error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }
    }
}

NesclPms.WebUI/Controllers/RoleAdminController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using NesclPms.WebUI.Infrastructure;
using NesclPms.WebUI.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace NesclPms.WebUI.Controllers
{
    [Authorize(Roles="admin")]
    public class RoleAdminController : ApplicationController
    {
        public ActionResult Index()
        {
            return View(RoleManager.Roles);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create([Required]string name)
        {
            if (ModelState.IsValid)
            {
                IdentityResult result
                    = await RoleManager.CreateAsync(new AppRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    AddErrorsFromResult(result);
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(string id)
        {
            AppRole role = await RoleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await RoleManager.DeleteAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return View("Error", result.Errors);
                }
            }
            else
            {
                return View("Error", new string[] { "Role Not Found" });
            }
        }

        private void AddErrorsFromResult(IdentityResult result)
        {
            foreach (string error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }

         public async Task<ActionResult> Edit(string id) {
            AppRole role = await RoleManager.FindByIdAsync(id);
            string[] memberIDs = role.Users.Select(x => x.UserId).ToArray();
            IEnumerable<AppUser> members
                = UserManager.Users.Where(x => memberIDs.Any(y => y == x.Id));
            IEnumerable<AppUser> nonMembers = UserManager.Users.Except(members);
            return View(new RoleEditModel
            {
                Role = role,
                Members = members,
                NonMembers = nonMembers
            });
         }

         [HttpPost]
         public async Task<ActionResult> Edit(RoleModificationModel model)
         {
             IdentityResult result;
             if (ModelState.IsValid)
             {
                 foreach (string userId in model.IdsToAdd ?? new string[] { })
                 {
                     result = await UserManager.AddToRoleAsync(userId, model.RoleName);
                     if (!result.Succeeded)
                     {
                         return View("Error", result.Errors);
                     }
                 }
                 foreach (string userId in model.IdsToDelete ?? new string[] { })
                 {
                     result = await UserManager.RemoveFromRoleAsync(userId,
                         model.RoleName);
                     if (!result.Succeeded)
                     {
                         return View("Error", result.Errors);
                     }
                 }
                 return RedirectToAction("Index");
             }
             return View("Error", new string[] { "Role Not Found" });
         }

        private AppUserManager UserManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<AppUserManager>();
            }
        }

        private AppRoleManager RoleManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<AppRoleManager>();
            }
        }
    }
}

NesclPms.WebUI/Views/Admin/Create.cshtml
@model NesclPms.WebUI.Models.CreateModel
@{ ViewBag.Title = "Create User";}

<h2>Create User</h2>

@Html.ValidationSummary(false)
@using (Html.BeginForm()) {
    <div class="form-group">
        <label>Employee ID</label>
        @Html.TextBoxFor(x => x.Name, new { @class = "form-control"})
    </div>
    <div class="form-group">
        <label>Name</label>
        @Html.TextBoxFor(x => x.LabelName, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Email</label>
        @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Password</label>
        @Html.PasswordFor(x => x.Password, new { @class = "form-control" })
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
    @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-default" })
}

NesclPms.WebUI/Views/Admin/Edit.cshtml
@model NesclPms.WebUI.Models.AppUser
@{ ViewBag.Title = "Edit"; }

@Html.ValidationSummary(false)
<h2>Edit User</h2>

<div class="form-group">
    <label>Id</label>
    <p class="form-control-static">@Model.Id</p>
</div>
@using (Html.BeginForm()) {
    @Html.HiddenFor(x => x.Id)

    <div class="form-group">
        <label>Name</label>
        @Html.TextBoxFor(x => x.LabelName, new { @class = "form-control" })
    </div>

    <div class="form-group">
        <label>Email</label>
        @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })
    </div>

    @*<div class="form-group">
        <label>Password</label>
        <input name="password" type="password" class="form-control" />
    </div>*@
    <button type="submit" class="btn btn-primary">Save</button>
    @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-default" })
}

NesclPms.WebUI/Views/Admin/Index.cshtml
@using NesclPms.WebUI.Models
@model IEnumerable<AppUser>
@{
    ViewBag.Title = "Index";
}

<ul class="nav nav-tabs">
    <li role="presentation" class="active">@Html.ActionLink("Users", "Index", "Admin", null, null)</li>
    <li role="presentation">@Html.ActionLink("Roles", "Index", "RoleAdmin", null, null)</li>
</ul>
<br/>

<div class="panel panel-primary">
    <div class="panel-heading">
        User Accounts
    </div>
    <table class="table table-striped">
        <tr><th>ID</th><th>Employee Id</th><th>Email</th><th></th></tr>
        @if (Model.Count() == 0)
        {
            <tr><td colspan="4" class="text-center">No User Accounts</td></tr>
        }
        else
        {
            foreach (AppUser user in Model)
            {
                <tr>
                    <td>@user.Id</td>
                    <td>@user.UserName</td>
                    <td>@user.Email</td>
                    <td>
                        @using (Html.BeginForm("Delete", "Admin",
                            new { id = user.Id }))
                        {
                            @Html.ActionLink("Edit", "Edit", new { id = user.Id },
                                    new { @class = "btn btn-primary btn-xs" })
                            <button class="btn btn-danger btn-xs"
                                    type="submit">
                                Delete
                            </button>
                        }
                    </td>
                </tr>
            }
        }
    </table>
</div>
@Html.ActionLink("Create", "Create", null, new { @class = "btn btn-primary" })

<br/>
<br/>